-- 주석   CTRL + /

/*
    여러 줄 주석
    ALT + SHIFT + C
*/

-- 나의 계정 보기
SHOW USER;

-- 사용자 계정 조회
/*
    - 조회 시
        SELECT [COLUMN(S)] FROM [TABLE_NAME]
*/
SELECT * FROM DBA_USERS;

SELECT USERNAME, USER_ID, PASSWORD
FROM DBA_USERS
WHERE USERNAME LIKE '%USER_';

-- 사용자 생성
/*
    ORACLE 12부터 일반사용자는 C##을 붙이도록 변경됨
    비밀번호에 특수문자 불가능
*/
CREATE USER C##USER2 IDENTIFIED BY "1234";

-- C## 키워드를 회피하는 설정
ALTER SESSION SET "_oracle_script" = TRUE;
/*
    계정명은 대소문자를 가리지 않음
    CREATE USER [USERNAME] IDENTIIED BY [PASSWORD];
*/
CREATE USER TJOEUN IDENTIFIED BY 1234;
CREATE USER CHUN_UNIV IDENTIFIED BY 1234;
CREATE USER javatest IDENTIFIED BY 1234;

-- 권한 부여
/*
    GRANT [RULE1, RULE2, RULE3...] TO [USERNAME]
    RESOURCE - 데이터
    CONNECT - 접근
*/
GRANT RESOURCE, CONNECT TO TJOEUN;
GRANT RESOURCE, CONNECT TO CHUN_UNIV;
GRANT CREATE VIEW TO TJOEUN;
GRANT CREATE VIEW TO CHUN_UNIV;

GRANT RESOURCE, CONNECT TO javatest;
GRANT CREATE VIEW TO javatest;

-- USER 삭제
--DROP USER C##USER2 CASCADE;

-- INSERT 시 생성된 유저에게 TABLESPACE 영역 할당할 지 지정
-- 무제한
-- 어디다 적어두고 필요할때 복붙하는 방식으로 사용해도 좋음
ALTER USER TJOEUN DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
ALTER USER CHUN_UNIV DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
ALTER USER javatest DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
-- 제한
--ALTER USER TJOEUN QUOTA 30M ON USERS;




-- DDL 사용자 만들기
ALTER SESSION SET "_oracle_script" = TRUE;
CREATE USER DDL IDENTIFIED BY 1234;
GRANT RESOURCE, CONNECT TO DDL;
ALTER USER DDL DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;