-- 1.
CREATE TABLE TB_CATEGORY (
  NAME VARCHAR2(10),
  USE_YN CHAR(1) DEFAULT 'Y'
);
-- 2.
CREATE TABLE TB_CLASS_TYPE (
  NO VARCHAR2(5) PRIMARY KEY,
  NAME VARCHAR2(10)
);
-- 3.
ALTER TABLE TB_CATEGORY ADD CONSTRAINT TB_CAT_PK PRIMARY KEY(NAME);
-- 4.
ALTER TABLE TB_CLASS_TYPE MODIFY NAME NOT NULL;
-- 5.
ALTER TABLE TB_CATEGORY MODIFY NAME VARCHAR2(20);
ALTER TABLE TB_CLASS_TYPE MODIFY NO VARCHAR2(10);
ALTER TABLE TB_CLASS_TYPE MODIFY NAME VARCHAR2(20);
-- 6.
ALTER TABLE TB_CATEGORY RENAME COLUMN NAME TO CATEGORY_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NAME TO CLASS_TYPE_NO;
-- 7.
ALTER TABLE TB_CATEGORY RENAME CONSTRAINT TB_CAT_PK TO PK_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME CONSTRAINT SYS_C007472 TO PK_NO;
-- 8.
INSERT INTO TB_CATEGORY VALUES('공학', 'Y');
INSERT INTO TB_CATEGORY VALUES('자연과학', 'Y');
INSERT INTO TB_CATEGORY VALUES('의학', 'Y');
INSERT INTO TB_CATEGORY VALUES('예체능', 'Y');
INSERT INTO TB_CATEGORY VALUES('인문사회', 'Y');
COMMIT;
-- 9.
ALTER TABLE TB_DEPARTMENT ADD CONSTRAINT FK_DEPARTMENT_CATEGORY 
  FOREIGN KEY(CATEGORY) REFERENCES TB_CATEGORY(CATEGORY_NAME);
-- 10.
CREATE VIEW VW_학생일반정보
  AS SELECT STUDENT_NO 학번, STUDENT_NAME 학생이름, STUDENT_ADDRESS 주소 FROM TB_STUDENT;
--DROP VIEW VW_학생일반정보;
SELECT * FROM "VW_학생일반정보";
-- 11.
CREATE VIEW VW_지도면담
  AS SELECT S.STUDENT_NAME 학생이름, D.DEPARTMENT_NAME 학과이름, NVL(P.PROFESSOR_NAME, '(지도교수 없음)') AS "지도교수 이름"
     FROM TB_STUDENT S, TB_PROFESSOR P, TB_DEPARTMENT D
     WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO(+)
      AND S.COACH_PROFESSOR_NO = P.PROFESSOR_NO(+)
     ORDER BY 2;
--DROP VIEW VW_지도면담;
SELECT * FROM "VW_지도면담";
-- 12.
CREATE VIEW VW_학과별학생수
  AS SELECT DEPARTMENT_NAME, COUNT(*) AS STUDENT_COUNT
    FROM TB_STUDENT S, TB_DEPARTMENT D
    WHERE D.DEPARTMENT_NO = S.DEPARTMENT_NO(+)
    GROUP BY DEPARTMENT_NAME
    ORDER BY 1;
-- DROP VIEW VW_학과별학생수
SELECT * FROM "VW_학과별학생수";
-- 13.
UPDATE VW_학생일반정보
SET 학생이름 = '김현수'
WHERE 학번 = 'A213046';
COMMIT;
--(SELECT STUDENT_ID FROM VW_학생일반정보 WHERE STUDENT_ID = )
SELECT * FROM TB_STUDENT
WHERE STUDENT_NAME = '김현수';
-- 14.
/*
  검색해본 결과에 의하면 
    WITH READ ONLY 옵션을 서브쿼리의 가장 마지막 부분에 추가하여
    VIEW 테이블에서의 데이터 수정을 막을 수 있다고 함
*/
-- 15. ???
SELECT CLASS_NO, SUM(STUDENTS) FROM (
SELECT CLASS_NO, COUNT(*) AS STUDENTS FROM TB_GRADE
GROUP BY LPAD(TERM_NO, 4), CLASS_NO)
GROUP BY CLASS_NO;